'use client'

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Global } from "@emotion/react";
import {global} from './globals'
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Global styles={global} />
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
